### ISSUE TITLE
The software does not record any video

### ISSUE THREAD

**Issue by mr-entropia** [lextrack/Simple-Screen-Recorder#11]
I tried all different combinations of encoders and file formats but everytime the result is the same: the software only records audio, no video at all. It doesn't throw any errors messages.

**Comment by Muscarv2** [comment]
Also having this problem, the first time I used the program it recorded video fine, but all other times since then it had only recorded audio. I've tried different video settings (avi/mkv, 30/60 fps, MPEG-4/H264, capture all screens on/off) but nothing works.

**Comment by lextrack** [comment]
@Muscarv2 @mr-entropia Could you try this version of the app that, when recording, displays the log in the command prompt to check for errors and take a screenshot of it? Honestly, I'm not sure what issue they are experiencing. I've tested the app on two computers and haven't had any problems. You can send the screenshot of the command prompt to my email: [ariel_munoz97@hotmail.com](mailto:ariel_munoz97@hotmail.com). Download the the test version: [Google Drive](https://drive.google.com/file/d/1ON7M4gD1x8AoHrk6YnZc4wiCEFsYKVcx/view?usp=sharing)

**Comment by f-michaut** [comment]
I have the exact same issue, downloaded it from the README link, and it only produces `MicrophoneAudio` and `SystemAudio` files, no video

**Comment by lstudley** [comment]
_20240425163717_  Same here, no video. Going to try as admin.
