### ISSUE TITLE
Does not record video

### ISSUE THREAD

**Issue by Rings4** [lextrack/Simple-Screen-Recorder#18]
This doesn't record video no matter which setting I use. Tried 1.2.6 and 1.2.5.

GTX 1080TI, Ryzen 7 5800X, Windows 10.

**Comment by lstudley** [comment]
_20240425163717_  Same here, no video. Going to try as admin. Win10

**Comment by lstudley** [comment]
update: _20240425202750_  
I rebuilt the project under VStudio 2022 community and I was able to record video.
I'm not sure if there's a path to something in the code that's not portable. I did find that I got an error "AL1065 long path..." even if long paths are enable in group policy on the pc, there's an issue with the "AL.exe" itself, microsoft assembly linker, in that it is not long-path capable. So I had to put the project in a 'shallow' directory ie "c:\sand\Simple-Screen-Recorder-master" and it cleaned/built and ran correctly.

**Comment by lstudley** [comment]
Thank you LexTrack!!!! this solves a need I've had for awhile, for a nice portable screen capture with both mic and system sounds merged. Awesome work!!!!!

**Comment by lextrack** [comment]
> update: _20240425202750_ I rebuilt the project under VStudio 2022 community and I was able to record video. I'm not sure if there's a path to something in the code that's not portable. I did find that I got an error "AL1065 long path..." even if long paths are enable in group policy on the pc, there's an issue with the "AL.exe" itself, microsoft assembly linker, in that it is not long-path capable. So I had to put the project in a 'shallow' directory ie "c:\sand\Simple-Screen-Recorder-master" and it cleaned/built and ran correctly.

Thank you very much for your help. I was investigating the issue with the paths, but I think the simplest solution is for the user to choose the Documents folder, for example, to save the app. I will update the app and the readme shortly
