### ISSUE TITLE
Recording stops if UAC is involved

### ISSUE THREAD

**Issue by gl4nce** [lextrack/Simple-Screen-Recorder#22]
Video recording stops without any notice if Windows UAC pops up. Looks like audio recording is not affected.

**Comment by lextrack** [comment]
> Video recording stops without any notice if Windows UAC pops up. Looks like audio recording is not affected.

I mention that in the README. I can find a way to solve that. To prevent Windows UAC prompts from interrupting recording, you should select the second-to-last option, which says "Notify me only when apps try to make changes to my computer (do not dim my desktop)". Or, if you want, completely disable it.

**Comment by gl4nce** [comment]
Ah sorry, didn't read the manual. My fault. Then it's all fine. :)
