### ISSUE TITLE
Wrong file size reported in github repository home page

### ISSUE THREAD

**Issue by bovirus** [lextrack/Simple-Screen-Recorder#4]
@lextrack 

Why in home repository page there is

Windows 7, 8.1, 10, 11 (64 bits) | v1.0.8 (**108 MB**) | [Download]

The program size is about 38 Mb.

**Comment by lextrack** [comment]
> @lextrack
> 
> Why in home repository page there is
> 
> Windows 7, 8.1, 10, 11 (64 bits) | v1.0.8 (**108 MB**) | [Download]
> 
> The program size is about 38 Mb.

38 Mb is the compress size, once you uncompressed the zip file, you get a folder with the entire size: 108 Mb
