### ISSUE TITLE
Autodetect language at startup

### ISSUE THREAD

**Issue by bovirus** [lextrack/Simple-Screen-Recorder#5]
@lextrack 

Could be possible to enable autodetect language at first program startup?

I installed v. 1.0.8 (that inlcude Italian language), but at first stratup it started in English and I have to change language to Italian.

My OS is Windows 11 Professional 64bit Italian.

**Comment by lextrack** [comment]
> @lextrack
> 
> Could be possible to enable autodetect language at first program startup?
> 
> I installed v. 1.0.8 (that inlcude Italian language), but at first stratup it started in English and I have to change language to Italian.
> 
> My OS is Windows 11 Professional 64bit Italian.

I tried to do that, but I can't :/ anyway, you have to change the language only the first time, then the language you have selected will be active any time you open the app
