### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by vkeychaudhari** [lextrack/Simple-Screen-Recorder#9]
After start recording, Getting the following runtime error, 

![image](https://user-images.githubusercontent.com/46781848/212845429-91e160f4-95cc-4535-b645-475372701008.png)

**Comment by lextrack** [comment]
I think it's something related to your VS version (you're using a preview version?). Try to run VS in Administrator mode or tick the option "System.Runtime.InteropServices.COMException" in debug exceptions settings.  ![Capture](https://user-images.githubusercontent.com/42826936/212905856-3bf23ac6-4fe2-48b7-9316-cd8a1f6838b4.PNG)

You can see more of that here:
[https://stackoverflow.com/questions/4281425/how-to-avoid-a-system-runtime-interopservices-comexception](url)
